version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run: git clone https://github.com/kidp2h/box-universe-client ./client
      - run: git clone https://github.com/kidp2h/box-universe-server ./server
      - run: cd ./server && yarn install && yarn build
      - run: cd ./client && yarn install && yarn build
  docker:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: cp .env.example .env
      - setup_remote_docker
      - run: cat .env
      - run: ls -a
      - run: docker-compose --env-file ./.env -f ./docker/docker-compose.yml build
workflows:
  manual:
    jobs:
      - docker

  
