version: 2.1
orbs:
  docker: circleci/docker@1.7.0

jobs:
  build:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run: git clone https://github.com/kidp2h/box-universe-client ./client
      - run: git clone https://github.com/kidp2h/box-universe-server ./server
      - run: cd ./server && yarn install && yarn build
      - run: cd ./client && yarn install && yarn build
  docker:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - docker/install-docker
      - setup_remote_docker:
          docker_layer_caching: true # should not be important
          version: 20.10.12
      - run: cp .env.example .env
      - run: cat .env
      - run: ls -a
      - run: docker compose --env-file ./.env -f ./docker/docker-compose.yml build
workflows:
  manual:
    jobs:
      - docker

  
