version: 2.1
orbs:
  docker: circleci/docker@1.7.0

jobs:
  compose:
    docker:
      - image: cimg/base:stable
    steps:
      - docker/install-docker-tools:
          install-docker-compose: true
  clone:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: git clone https://github.com/kidp2h/box-universe-client ./client
      - run: git clone https://github.com/kidp2h/box-universe-server ./server
      - run: ls -a
      - run: cd server && ls -a
  yarn:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run: npm install -g yarn@latest
  server:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run: ls
      - run: cd ./server
      - run: yarn install --production
      - run: yarn build
      - run: yarn start:prod
  client:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run: ls
      - run: cd ./client
      - run: yarn install --production
      - run: yarn build
      - run: yarn start
workflows:
  prerequisite:
    jobs:
      - clone
      - yarn
  manual:
    jobs:
      - client
      - server


  
