version: 2.1
orbs:
  docker: circleci/docker@1.7.0

jobs:
  compose:
    docker:
      - image: cimg/base:stable
    steps:
      - docker/install-docker-tools:
          install-docker-compose: true
  clone:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: sh ./scripts/production.sh
      - run: ls -a

workflows:
  build:
    jobs:
      - compose
      - clone

  
