version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run: git clone https://github.com/kidp2h/box-universe-client ./client
      - run: git clone https://github.com/kidp2h/box-universe-server ./server
      - run: cd ./server && yarn install && yarn build
      - run: cd ./client && yarn install && yarn build
workflows:
  manual:
    jobs:
      - build

  
